### ISSUE TITLE
Requesting no password prompts for db query

### ISSUE THREAD

**Issue by joshmullis** [jeffmcutter/cf_shortcuts#12]
Hey Jeff!

When running cfgrep-request on a DB that does not have the default cloudforms password, the user is prompted to enter the password.

Here's what I did to fix it, but it may not be portable for others use.

```
    #TASK_IDS=$(echo "select id from miq_request_tasks where miq_request_id = $REQUEST_ID" | rails db | awk '$1!="id" && !/^---/ && !/^\(/ {print $1}' | sort -n)
    TASK_IDS=$(psql -d vmdb_production -c "select id from miq_request_tasks where miq_request_id = $REQUEST_ID" | awk '$1!="id" && !/^---/ && !/^\(/ {print $1}' | sort -n)
```

Let me know what you think.
Thanks!
-josh

**Comment by jeffmcutter** [comment]
I wonder what would cause rails db to need a password in that case.  If the above always works we could change it to that instead.

**Comment by joshmullis** [comment]
Maybe the rails db has the default cf pass in a config?
Whatever you think is best. :)

**Comment by jeffmcutter** [comment]
I still need to figure out a way to deal with it.  I was about to use the psql method as suggested and realized it won't work when using a dedicated db appliance without the app on it.

**Comment by jeffmcutter** [comment]
On second thought that might be viable if I change to use psql everywhere instead of rails db.  Will need to investigate.

**Comment by jeffmcutter** [comment]
Tested OK on dedicated db appliance.  Commit 46b110c implements this change in 2 places.
